# Generated by Django 3.2.4 on 2021-09-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apod',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('hdurl', models.URLField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('media_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MRP',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sol', models.IntegerField(blank=True, null=True)),
                ('earth_date', models.DateField(blank=True, null=True)),
                ('camera_id', models.IntegerField(blank=True, null=True)),
                ('camera_name', models.CharField(blank=True, max_length=50, null=True)),
                ('camera_full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(max_length=500)),
                ('rover_id', models.IntegerField(blank=True, null=True)),
                ('rover_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rover_landing_date', models.CharField(blank=True, max_length=50, null=True)),
                ('rover_launch_date', models.CharField(blank=True, max_length=50, null=True)),
                ('rover_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
